#!/usr/bin/env php
<?php
/**
 * 控制台入口11
 *
 * @author    XueronNi <xueronni@uniondrug.cn>
 * @copyright 2018
 */
set_time_limit(0);
date_default_timezone_set('PRC');

// autoload composer
$autoload = __DIR__ . '/../../../../../vendor/autoload.php';
if (file_exists($autoload)) {
    define('COMPOSER_INSTALL', $autoload);
}

if (!defined('COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

include COMPOSER_INSTALL;
/**
 * This code
 *
 * __DIR__ . '/app'
 *
 * is test code.
 */
try {
    define("INDEX_PATH", __DIR__ . '/../../../../../public');
    define("APP_PATH", __DIR__ . '/../../../../../app');
    define("CONFIG_PATH", __DIR__ . '/../../../../../config');
    define("LOG_PATH", __DIR__ . '/../../../../../log');
    $di = new \Phalcon\Di\FactoryDefault();
    $application = new \Healthplat\Tool\Application($di);
    $console = new \Healthplat\Tool\Commands\Command($application);
    $console->run();

} catch (Throwable $e) {
    echo PHP_EOL;
    echo "Error: " . $e->getMessage() . PHP_EOL;
    //echo PHP_EOL;
    echo " File: " . $e->getFile() . PHP_EOL;
    echo " Line: " . $e->getLine() . PHP_EOL;
    echo PHP_EOL;
}